site_name: NEXT-Net Documentation
site_description: Documentation for NEXT-Net.
theme: 
  name: 'material'
  custom_dir : docs/overrides
  palette:
    # You can pick a scheme: light, dark, etc.
    scheme: default
    primary: '#C80019'
    accent: '#C80019'
  logo: assets/images/logo.png
  favicon: assets/images/logo_web.png
repo_url: https://github.com/oist/NEXTNetPy
repo_name: NEXTNetPy

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - References:
      - Simulations on Static Networks: simulations_static.md
      - Simulations on Temporal Networks: simulations_temporal.md
      - Transmission Distributions: transmission_distributions.md
      - Networks: networks.md
      - Tools: tools.md
  - Tutorials:
      - Clustered Networks: tutorials/clustered.ipynb
      - Activity Driven Networks: tutorials/activity_driven.ipynb
      - Temporal Networks From Data: tutorials/temporal_empirical.ipynb

plugins:
    - mkdocs-jupyter:
        execute: true
        ignore_h1_titles: True
        include_source: True
        custom_mathjax_url: "../../assets/javascripts/MathJax-3.2.2/es5/tex-mml-chtml.js"

markdown_extensions:
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra_css:
  - css/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/MathJax-3.2.2/es5/tex-mml-chtml.js